fix: handle partial prompt response and add unit tests
atsign-foundation/at_libraries pull request #185
Opened 2022-06-28 04:37 UTC by kalluriramkumar

With the current logic in `messageHandler`, if a partial prompt response is received, then the partial responses gets appended to subsequent responses.

**- What I did**
1. Added an additional IF condition to check a response is a partial response. If partial response, then do not append to buffer.

**- How I did it**
1. Added an IF condition that checks if responses contains a new line character(terminating character) and ends with `@`. If the response do not contain new line character and ends with `@` then the response is considered as partial prompt response.

**- How to verify it**

**- Description for the changelog**

2022-06-29 08:02 UTC, gkc requested changes

2022-06-29 08:02 UTC, gkc commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +          : bufferLength = (_buffer.length() + data.length) as int;
I think the above can be simplified to `bufferLength = (_buffer.length() + data.length) as int;`

2022-06-29 08:02 UTC, gkc commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +    if (_isInCompletePromptReceived) {
Should never be possible. The whole point of waiting for newline is that once we receive a full response line terminated by '\n', we *know* that there is a prompt at the start of the line, which we need to trim.

We have two types of info available to us to help us easily trim the prrompt

1) We know that messages from the server, after the prompt portion, always start with `data:` or `error:` or `notification:`. The Java SDK uses this information
2) We know that if we have an unauthenticated connection the prompt will be '@' but if we have an authenticated connection the prompt will be '@<atSign>@'

2022-06-29 08:02 UTC, gkc commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +  String _trimPrompt(String result) {
Implementation is more complex than it needs to be. See comment below

2022-06-29 09:06 UTC, kalluriramkumar commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +    if (_isInCompletePromptReceived) {
Refactored the code and used 'data:' or 'error:' or 'stream:' to find the start of server responses.

2022-06-29 09:08 UTC, kalluriramkumar commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +          : bufferLength = (_buffer.length() + data.length) as int;
Refactored the code as mentioned.

2022-06-29 09:08 UTC, sitaram-kalluri commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +  String _trimPrompt(String result) {
Refactored the code and pushed the changes as mentioned.

2022-06-29 09:26 UTC, gkc requested changes

2022-06-29 09:26 UTC, gkc commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +    _buffer.append(data);
You need to process the data one byte at a time in order to avoid bug with situation where there is more than one newLine

2022-06-29 09:26 UTC, gkc commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +      result = utf8.decode(_buffer.getData());
Nope, as I said before, you can only decode what you know is decodable - i.e. everything up to the newline

See the algorithm I proposed in an earlier review

2022-06-30 10:57 UTC, gkc requested changes

2022-06-30 10:57 UTC, gkc commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +    result = result.trim();
Please only trim the \n

2022-06-30 10:57 UTC, gkc commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +        _buffer.clear();
Suggest we now add `_buffer.addByte(element);` here as well, so that the '@' is at the start of the next buffer

2022-06-30 10:57 UTC, gkc commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +    //4. Add the result to queue.
We used to look at the whole data and break it on '\n'

What if we now do this:
```
Look at the whole data and look for the *LAST INDEX OF* '\n'
If not found
    copy the entire data into buffer
else
    copy the data from [start to last index of '\n'] into buffer
    Then start the for loop from [last index of '\n']
endif
```

2022-06-30 16:46 UTC, kalluriramkumar commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +    //4. Add the result to queue.
@gkc : The pseudo code fails in the following scenario:
For the server response: `data:@bob:phone@alice\n@alice@`, If the `data:@bob:phone@alice\n` comes in packet-1 and `@alice@` comes in packet-2. 

When the packet -1 arrives, the control goes into else block and `data:@bob:phone@alice\n` goes into buffer. when packet-2 comes, `@alice@` also goes into buffer and it keeps waiting for the terminating character resulting in time out exception.

2022-07-01 08:10 UTC, gkc commented on at_lookup/lib/src/connection/outbound_message_listener.dart
> +    //4. Add the result to queue.
```
Look at the whole data and look for the *LAST INDEX OF* '\n'
If not found
    Run the for loop on all of the data
else
    copy the data from [start to last index of '\n'] into buffer
    Then start the for loop from [last index of '\n']
endif
```

2022-07-04 10:33 UTC, gkc approved these changes
I think we're good to go, here; we need a solid block of apps testing now and need to be on the lookout for situations we hadn't anticipated

2022-07-04 10:39 UTC, merged