fix: Removed race condition related to management of outbound connection state after timeouts
atsign-foundation/at_libraries pull request #251
Opened 2022-11-21 14:46 UTC by gkc

fixes #250 

**- What I did**
* fix: Removed race condition related to management of OutboundConnection state after timeouts
* style: a few miscellaneous style / readability / maintainability changes
* fix: add the `unawaited_futures` lint rule to detect where we are not using `await` (usually accidentally). **Note:** This rule would have flagged the missing 'awaits' which triggered the bug 

**- How I did it**
* fix: (The fix itself) : Added missing `await`s to `OutboundMessageListener.read` which prevent problems caused (very rarely) by race condition where the OutboundConnection should have been closed but hasn't yet been closed, therefore making a rapidly-subsequent `write()` believe that the connection is still valid, and other weirdnesses to ensue
* test: Add a bunch of tests to verify
  * that isInvalid is set on the OutboundConnection after transientWaitTime timeout BEFORE the OutboundMessageListener.read() returns
  * that isInvalid is set on the OutboundConnection after maxWaitTime timeout BEFORE the OutboundMessageListener.read() returns
  * that an attempt to write to an outbound connection which has had a timeout will throw a ConnectionInvalidException
* test: Add a `@visibleForTesting Duration? delayBeforeClose;` variable to OutboundMessageListener to allow us to inject a pause before actually closing a connection. In turn makes it possible to reliably reproduce race conditions (if they exist) related to program code trying to write to a connection which should be closed but has not yet been marked as closed for whatever reason.

* fix: New lint rule flagged lots of warnings about missing awaits in test code. Added missing awaits to eliminate the warnings.
* fix: add the `unawaited_futures` lint rule to detect where we are not using `await` (usually accidentally). 
* fix: use finally block in close() to set isClosed to true on the connection metadata
* feat: log an INFO message when a new connection has been created (we already log an INFO message when we are about to try to create a new connection)
* style: remove lint warnings for spelling in test descriptions
* fix: eliminated two lint warnings by making privateKey and cramSecret initializing formal parameters in AtLookupImpl constructorImpl constructor
* fix: set transient wait time to 4 seconds and max wait time to 10 seconds for response to 'cram' verb
* fix: set transient wait time to 4 seconds and max wait time to 10 seconds for response to 'from' verb
* test: Reworded to improve clarity of mutex_test.dart output
* test: Speed up the outbound_message_listener_test unit tests by setting transientWaitTime and maxWaitTime parameters when calling `OutboundMessageListener.read()`
* refactor: In AtLookupImpl, use the same mutex for all requests including cram and pkam auth. (They all use the same connection, they all require responses to be received before next request can be sent, so they can and should use the same mutex).

**- How to verify it**
* All tests pass. If you're curious and want to prove that the tests will fail without the fix, then you can remove the `await`s in outbound_message_listener.dart at lines 127 and 136 and re-run the unit tests, at which point three of them will fail.

**- Description for the changelog**
fix: Removed race condition related to management of outbound connection state after timeouts

2022-11-21 15:19 UTC, cpswan approved these changes, later dismissed

2022-11-22 11:15 UTC, murali-shris requested changes

2022-11-22 11:15 UTC, murali-shris commented on packages/at_lookup/lib/src/at_lookup_impl.dart
> +  Future<bool> authenticatePKAM(String? privateKey) async {
if a developer uses existing version of at_client or at_client_mobile in pub.dev and runs pub get in the app pubspec.yaml and published version of at_lookup is pulled( after this PR merge) won't the rename cause breakage?

2022-11-22 13:13 UTC, gkc commented on packages/at_lookup/lib/src/at_lookup_impl.dart
> +  Future<bool> authenticatePKAM(String? privateKey) async {
Yes - I just realized that when I tested at_client_sdk against this branch of at_lookup. I have reverted the method renames

2022-11-22 13:51 UTC, murali-shris submitted a review, later dismissed

2022-11-22 14:23 UTC, murali-shris approved these changes

2022-11-22 14:29 UTC, gkc commented
[Tested at_client against this branch](https://github.com/atsign-foundation/at_client_sdk/actions/runs/3524051445) - all good. Merging to trunk.

2022-11-22 14:29 UTC, merged