fix: changes to enroll syntax
atsign-foundation/at_libraries pull request #391
Opened 2023-08-03 09:40 UTC by sitaram-kalluri

**- What I did**
- Modify enroll verb to accept a json for params. Added new class in at_commons EnrollParams.dart
- Rename the enrollApprovalId to enrollmentId for naming consistency
- Add "list" to "EnrollOperationEnum"
- Update the unit tests to for the new enroll verb syntax
- Export "enroll_params.dart" file

2023-08-03 10:50 UTC, gkc commented on packages/at_commons/lib/src/verb/syntax.dart
> +      //  To ignore ":" if operation is list
To be precise, this is actually to require ":" if operation is request|approve|deny|revoke

2023-08-03 12:51 UTC, gkc requested changes

2023-08-03 12:51 UTC, gkc commented on packages/at_commons/lib/src/verb/syntax.dart
> +      //  if operation is request|approve|deny|revoke
I didn't mean for you to literally transcribe what I wrote :-)

How about, `Look-behind to require ':' if operations is request|approve|deny|revoke`

On looking at this again, shouldn't we also require params when operation is request|approve|deny|revoke ?

An alternative regex would be to require `enroll:` then require either `list$` or `(request|approve|deny|revoke):(params fragment)$` which might be simpler to maintain

2023-08-03 13:02 UTC, sitaram-kalluri commented on packages/at_commons/lib/src/verb/syntax.dart
> +      //  if operation is request|approve|deny|revoke
Is the following regex looks good?
```^enroll:(?<operation>(list$)|(request|approve|deny|revoke|):)(?<enrollParams>.+)?$```

2023-08-03 13:05 UTC, gkc commented on packages/at_commons/lib/src/verb/syntax.dart
> +      //  if operation is request|approve|deny|revoke
I think you need to write some unit tests

2023-08-03 13:47 UTC, sitaram-kalluri commented on packages/at_commons/lib/src/verb/syntax.dart
> +      //  if operation is request|approve|deny|revoke
We have unit tests in "packages/at_commons/test/syntax_test.dart" to verify the enroll verb syntax. Will test the changes and add more tests to it.

2023-08-04 06:57 UTC, gkc approved these changes

2023-08-04 06:57 UTC, merged