feat: at_lookup apkam changes
atsign-foundation/at_libraries pull request #394
Opened 2023-08-17 19:34 UTC by murali-shris

**- What I did**
- apkam changes in at_lookup
**- How I did it**
- added an optional parameter enrollmentId to pkamAuthenticate method in at_lookup
- added getter/setter for enrollmentId in at_lookup which will be used in at_client - remote_secondary,monitor for setting enrollmentId
- introduced PkamVerbBuilder for constructing pkam command in at_lookup_impl.dart
- added executeCommand to at_lookup interface
**- How to verify it**
- added dependency overrides in at_client and verify github actions run
https://github.com/atsign-foundation/at_client_sdk/pull/1107

TODO
- Replace at_chops dependency overrides with published version

2023-08-20 23:34 UTC, gkc requested changes
Similar changes will need to be made in Monitor class in at_client package. Please can you link that PR to this one and vice versa?

2023-08-20 23:35 UTC, gkc requested changes
Tests?

2023-08-21 05:56 UTC, murali-shris commented
> Similar changes will need to be made in Monitor class in at_client package. Please can you link that PR to this one and vice versa?

I have done changes in at_client. Writing tests pending. I will link the PR once ready.

2023-08-21 05:56 UTC, murali-shris commented
> Tests?

I will write the tests in at_client functional tests

2023-08-21 07:03 UTC, murali-shris commented
> Similar changes will need to be made in Monitor class in at_client package. Please can you link that PR to this one and vice versa?

https://github.com/atsign-foundation/at_client_sdk/pull/1108
PR is in draft

2023-08-21 08:44 UTC, gkc commented
> > Tests?
> 
> I will write the tests in at_client functional tests

There should be some unit tests in this package also.

2023-08-21 15:20 UTC, murali-shris commented
> > > Tests?
> > 
> > 
> > I will write the tests in at_client functional tests
> 
> There should be some unit tests in this package also.

I tried writing unit test for at_lookup
https://gist.github.com/murali-shris/b64138f8e6da3181d648f7abb39090f3

in createConnection() method, messageListener is instantiated inside the method and mock listener is not picked up.

Should i try refactoring at_lookup_impl to make it unit testable or write functional tests for at_lookup package?

2023-08-21 17:30 UTC, gkc commented
> > > > Tests?
> > > 
> > > 
> > > I will write the tests in at_client functional tests
> > 
> > 
> > There should be some unit tests in this package also.
> 
> I tried writing unit test for at_lookup https://gist.github.com/murali-shris/b64138f8e6da3181d648f7abb39090f3
> 
> in createConnection() method, messageListener is instantiated inside the method and mock listener is not picked up.
> 
> Should i try refactoring at_lookup_impl to make it unit testable or write functional tests for at_lookup package?

Make it unit testable please. Suggest adding a "socketListenerFactory" along the same lines as was done for the "socketFactory" when that was added.

2023-08-22 07:47 UTC, murali-shris commented
> > > > > Tests?
> > > > 
> > > > 
> > > > I will write the tests in at_client functional tests
> > > 
> > > 
> > > There should be some unit tests in this package also.
> > 
> > 
> > I tried writing unit test for at_lookup https://gist.github.com/murali-shris/b64138f8e6da3181d648f7abb39090f3
> > in createConnection() method, messageListener is instantiated inside the method and mock listener is not picked up.
> > Should i try refactoring at_lookup_impl to make it unit testable or write functional tests for at_lookup package?
> 
> Make it unit testable please. Suggest adding a "socketListenerFactory" along the same lines as was done for the "socketFactory" when that was added.



> > > > > Tests?
> > > > 
> > > > 
> > > > I will write the tests in at_client functional tests
> > > 
> > > 
> > > There should be some unit tests in this package also.
> > 
> > 
> > I tried writing unit test for at_lookup https://gist.github.com/murali-shris/b64138f8e6da3181d648f7abb39090f3
> > in createConnection() method, messageListener is instantiated inside the method and mock listener is not picked up.
> > Should i try refactoring at_lookup_impl to make it unit testable or write functional tests for at_lookup package?
> 
> Make it unit testable please. Suggest adding a "socketListenerFactory" along the same lines as was done for the "socketFactory" when that was added.

Done. please review.

at_client test run pointing to this branch of at_lookup
https://github.com/atsign-foundation/at_client_sdk/pull/1109

2023-08-22 09:18 UTC, gkc approved these changes

2023-08-22 09:18 UTC, merged