feat: introduce cramAuthenticate and close into atLookup interface
atsign-foundation/at_libraries pull request #433
Opened 2023-10-19 13:32 UTC by srieteja

closes https://github.com/atsign-foundation/at_libraries/issues/421
**- What I did**
- Introduce cramAuthenticate() and close() into AtLookup interface
- Deprecate method authenticate_cram from AtlookupImpl
- Upgrade dependencies at_commons to v3.0.57 and at_chops to v1.0.5

**- Description for the changelog**

feat: introduce cramAuthenticate and close into atLookup interface

2023-10-20 08:34 UTC, murali-shris requested changes

2023-10-20 08:34 UTC, murali-shris commented on packages/at_lookup/lib/src/at_lookup.dart
> +  Future<bool> cramAuthenticate(var secret);
can you rename param from var secret to String secret

2023-10-20 16:12 UTC, srieteja commented on packages/at_lookup/lib/src/at_lookup.dart
> +  Future<bool> cramAuthenticate(var secret);
change has been made as part of [6deb45f](https://github.com/atsign-foundation/at_libraries/pull/433/commits/6deb45fd82f18e34b0f25c9491a8033bbc0c4fe6)

2023-10-26 07:49 UTC, murali-shris approved these changes

2023-10-26 07:50 UTC, merged