fix: Remove metadata fields in verb builders
atsign-foundation/at_libraries pull request #471
Opened 2023-12-07 05:15 UTC by sitaram-kalluri

**- What I did**
- Remove AtKey fields and metadata fields from the verb builders. Use AtKey instance in "AbstractVerbBuilder" to set the key.
- Since "key" in AtKey cannot be null, removed "?" which indicates that key can be null, and marked it as late.
- Removed `static const String atOperation = 'operation` from "at_constants.dart" file because it is redundant.
- Remove "?" for "isBinary" and "isEncrypted" fields default them to false.
- In AtClient pacakge,  AtKey.Metadata is verififed for null check and if null assigned to `Metadata()` . Initialized Metadata field to remove the null check in at_client methods.
- Since metadata is removed from verb builders, removed `packages/at_commons/lib/src/verb/metadata_using_verb_builder.dart` file which is not needed. 
- Uptake the at_commons changes into at_lookup.
- Modify the tests in at_commons.

Raised draft PR's in at_client_sdk and at_server to validate the changes:

at_server: https://github.com/atsign-foundation/at_server/pull/1688

at_client: https://github.com/atsign-foundation/at_client_sdk/pull/1179

2023-12-08 06:57 UTC, murali-shris commented
in verb builders replace string concatenation with string builder

2023-12-08 06:57 UTC, murali-shris requested changes

2023-12-08 06:57 UTC, murali-shris commented on packages/at_lookup/lib/src/at_lookup_impl.dart
>      var builder = DeleteVerbBuilder()
at_lookup changes you can move to separate PR.
at_lookup dependency on at_commons 4.x is a minor version release for at_lookup?

2023-12-11 06:08 UTC, sitaram-kalluri commented
> in verb builders replace string concatenation with string builder

This change is completed and pushed the changes.

2023-12-11 06:09 UTC, sitaram-kalluri commented on packages/at_lookup/lib/src/at_lookup_impl.dart
>      var builder = DeleteVerbBuilder()
- Sure Murali, WIll move the at_lookup changes to a new PR.
- At_lookup can pusblished as a minor version because we are not introducing any breaking changes.

2023-12-11 06:59 UTC, murali-shris submitted a review, later dismissed

2023-12-11 10:26 UTC, murali-shris approved these changes

2023-12-11 10:26 UTC, merged