feat: Modify "executeCommand" to throw exception on error response from atServer (as "executeVerb" does)
atsign-foundation/at_libraries pull request #507
Opened 2024-01-29 13:45 UTC by sitaram-kalluri

**- What I did**
- Currently, the server response are only parsed in the "executeVerb" method. But the requests that sent via the "executeCommand" are not parsed. The responses are returned as is to the client.
- Modify the "executeCommand" method to parse the server response and then return the response or the exception.

**- How I did**
- Move the logic that parses the server response in the "executeVerb" method to a private method "_verbResponseHandler". 
- Move the logic that parses the error response to a private method "_errorResponseHandler". The "_verbResponseHandler" invokes the "_errorResponseHandler" if the server response starts with "error:".
- Pass the response received via the execute command to _verbResponseHandler to parse the server response.

2024-01-29 14:04 UTC, gkc requested changes
1. Why have you removed the backwards compatibility?
2. Is this just intended as a refactoring? Because it seems like the existing behaviour is exactly what you are describing (parse the error response and throw an exception)

2024-01-29 16:09 UTC, sitaram-kalluri commented
> 1. Why have you removed the backwards compatibility?
> 2. Is this just intended as a refactoring? Because it seems like the existing behaviour is exactly what you are describing (parse the error response and throw an exception)

@gkc : Since there is a TODO to remove the code in next release and the client versions above v3.0.37 (currently 3.0.75) are capable of handling the JSON encoding the server error responses, it is mostly unlikely to encounter the format exception. Hence removed the code. However, since this is not a major release, please let me know if wanted me to put back the code related to backward compatibility.

2024-01-29 17:22 UTC, gkc commented
> > 1. Why have you removed the backwards compatibility?
> 
> > 2. Is this just intended as a refactoring? Because it seems like the existing behaviour is exactly what you are describing (parse the error response and throw an exception)
> 
> 
> 
> @gkc : Since there is a TODO to remove the code in next release and the client versions above v3.0.37 (currently 3.0.75) are capable of handling the JSON encoding the server error responses, it is mostly unlikely to encounter the format exception. Hence removed the code. However, since this is not a major release, please let me know if wanted me to put back the code related to backward compatibility.

Ok - so the PR is not a fix, it's removing unnecessary code which is there for compatibility with old atServers?

2024-01-29 17:28 UTC, sitaram-kalluri commented
> > > 1. Why have you removed the backwards compatibility?
> > 
> > 
> > > 2. Is this just intended as a refactoring? Because it seems like the existing behaviour is exactly what you are describing (parse the error response and throw an exception)
> > 
> > 
> > @gkc : Since there is a TODO to remove the code in next release and the client versions above v3.0.37 (currently 3.0.75) are capable of handling the JSON encoding the server error responses, it is mostly unlikely to encounter the format exception. Hence removed the code. However, since this is not a major release, please let me know if wanted me to put back the code related to backward compatibility.
> 
> Ok - so the PR is not a fix, it's removing unnecessary code which is there for compatibility with old atServers?

@gkc : Yes, But, just not introduce any breaking change, I am adding the changes related to backward compatibility , will defer this to later.

2024-01-29 17:51 UTC, gkc commented
please do the backwards compatibility change also. What confused me a lot here is that the PR title says it's a fix, when it is not. Please update the PR's title and description to correctly reflect its purpose

2024-01-29 17:53 UTC, sitaram-kalluri commented
> please do the backwards compatibility change also. What confused me a lot here is that the PR title says it's a fix, when it is not. Please update the PR's title and description to correctly reflect its purpose

Sure, Gary. Added back the backward compatibility change. Now the PR contains only the fix that handles the error responses from server in the executeCommand command to return the exception.

2024-01-29 20:25 UTC, gkc commented
Please update the PR's title and description to correctly reflect its purpose

2024-01-29 20:28 UTC, gkc commented
The PR description says:

Add verb response handler to handle the server responses.
Add "_verbResponseHandler" to handle the server responses
If response starts with "data:" then return the response.
If the response starts with "error:" parse the exception and return the appropriate exception.

That's the existing functionality. But the PR is not adding anything new; it is removing some code which has become unnecessary over time.

2024-01-31 10:43 UTC, gkc reviewed
LGTM. Please confirm that at_client tests are successful against this branch

2024-02-04 06:37 UTC, sitaram-kalluri commented
> LGTM. Please confirm that at_client tests are successful against this branch

@gkc : Ran tests in at_client against this branch and the runs are successful.

2024-02-04 14:32 UTC, gkc approved these changes

2024-02-04 14:33 UTC, merged