fix: Null pointer exception when pubKeyHash is null
atsign-foundation/at_libraries pull request #523
Opened 2024-02-22 06:33 UTC by sitaram-kalluri

**- What I did**
- Fixes https://github.com/atsign-foundation/at_libraries/issues/521

**- How I did it**
- when `fullJson` is set to true (the default value), the resultant map contains all the fields. If the value is not set, null is populated. To be consistent with the other fields, changed the implementation as `pubKeyHash!.toJson()` to `pubKeyHash?.toJson()`

**- How to verify it**
- Raised a draft PR in at_client_sdk to verify the changes: https://github.com/atsign-foundation/at_client_sdk/pull/1245
- Added unit tests to assert the changes.

**- Description for the changelog**
- fix: Null pointer exception when pubKeyHash is null

2024-02-22 11:06 UTC, gkc requested changes
Please add unit tests which would have caught this issue had they existed.

2024-02-23 04:26 UTC, sitaram-kalluri commented
> Please add unit tests which would have caught this issue had they existed.

Added unit tests and also changed the  approach in fix the bug.

when fullJson is set to true (the default value), the resultant map contains all the fields. If the value is not set, null is populated. To be consistent with the other fields, changed the implementation as `pubKeyHash!.toJson()` to `pubKeyHash?.toJson()`

2024-02-23 11:32 UTC, gkc requested changes

2024-02-23 11:32 UTC, gkc commented on packages/at_commons/test/at_key_test.dart
> +      ..isBinary = true;
Please extend to set all fields on the metadata and expect on all of them later

2024-02-24 11:08 UTC, sitaram-kalluri commented on packages/at_commons/test/at_key_test.dart
> +      ..isBinary = true;
The change is implemented in https://github.com/atsign-foundation/at_libraries/pull/523/commits/8f9f23f468c445106d5f94347e2b42477b9e17f8

2024-02-24 13:23 UTC, gkc approved these changes

2024-02-24 13:23 UTC, merged