fix: save enrollment details to local keystore
atsign-foundation/at_libraries pull request #599
Opened 2024-06-18 07:00 UTC by murali-shris

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

2024-07-01 13:36 UTC, sitaram-kalluri submitted a review, later dismissed

2024-07-17 15:54 UTC, srieteja commented
waiting for https://github.com/atsign-foundation/at_libraries/pull/606 to be merged into this branch.

2024-07-19 08:59 UTC, gkc commented
> waiting for #606 to be merged into this branch.

#606 has been merged

2024-07-19 09:01 UTC, gkc commented
> > waiting for #606 to be merged into this branch.
> 
> #606 has been merged to trunk

@srieteja I'll resolve the merge conflicts and merge trunk into this branch

2024-07-19 09:06 UTC, srieteja commented
@gkc once the conflicts are resolved, functional tests will fail as a result of changes. Working on updating them

2024-07-19 09:09 UTC, gkc commented
> @gkc once the conflicts are resolved, functional tests will fail as a result of changes. Working on updating them

I've fixed all the ripple effects and pushed to the branch

2024-07-19 09:20 UTC, gkc requested changes
1. The PR description explains what has been done, but not _why_. Please add an explanation of the problem that is being addressed here (or link to a ticket which has that explanation).
2. This PR handles writing to the keystore ... is the intent that there will be code elsewhere which reads this information from the keystore?
3. The information is currently written to `'${enrollmentResponse.enrollmentId}.new.enrollments.__manage${atClient!.getCurrentAtSign()}'`
  - Given that this is purely for local client-side use, we should use a local key
  - And we should not be using the __manage namespace

2024-07-19 10:02 UTC, murali-shris commented
> 1. The PR description explains what has been done, but not _why_. Please add an explanation of the problem that is being addressed here (or link to a ticket which has that explanation).
> 2. This PR handles writing to the keystore ... is the intent that there will be code elsewhere which reads this information from the keystore?
> 3. The information is currently written to `'${enrollmentResponse.enrollmentId}.new.enrollments.__manage${atClient!.getCurrentAtSign()}'`
> 
> * Given that this is purely for local client-side use, we should use a local key
> * And we should not be using the __manage namespace

#1 added to the PR description
#2 the local key which store enrollment details will be read from LocalSecondary --> isEnrollmentAuthorizedForOperation(..) in at_client
#3 agreed. Will make the change

2024-07-25 13:02 UTC, gkc commented on tests/at_onboarding_cli_functional_tests/test/enrollment_test.dart
> +      expect(() async => await client?.put(buzzKey, 'value'),
it's cleaner to do `await expectLater(...)`

2024-07-25 13:06 UTC, gkc requested changes
Please un-skip the test(s) in test/at_onboarding_cli_test.dart

2024-07-25 15:52 UTC, gkc approved these changes
LGTM

2024-07-25 16:06 UTC, merged