fix: Check of write permission of atKeys file path when submitting enroll request
atsign-foundation/at_libraries pull request #690
Opened 2024-10-14 07:13 UTC by sitaram-kalluri

**- What I did**
- When submitting the enrollment request, checks for the write permissions of the atKeys filepath. If the filePath has write permission, then continues with submission of enrollment request, else logs error and quits.

**- How I did it**
- Introduce "isWritable" method which attempts to create the directories for the given file if they do not exist, and then tries to open the file in write mode to verify write permissions. If the file can be opened for writing, it is immediately closed and deleted. In `AtOnboardingServiceImpl._generateAtKeysFile` method, there is a check which returns error if the file already exists. Therefore, delete the file here after checking for write permissions.
- Removed the logic that checks for the existence of the atKeys file from the enroll method, as this verification will now be handled by the isWritable method when creating the atKeys file to confirm write permissions.

**- How to verify it**
- Added the below unit tests to assert the behavior of the isWritable method:
   -  A test to verify isWritable returns false if directory has only read-only permissions
   - A test to verify isWritable returns false if file already exists in the directory
   - A test verify isWritable returns true if directory does not have a file already

**- Description for the changelog**
- fix: Check of write permission of atKeys file path when submitting enroll request

2024-10-14 11:18 UTC, gkc requested changes
@sitaram-kalluri I think the logic here is faulty. Consider the following scenario. 
. User onboards an atsign using onboard command - standard atKeys file created
. On the same host, the user attempts an enrollment using the enroll command leaving the keys file as default
. isWritable confirms the standard atKeys file is writable, and then deletes it
. the original atKeys file is now gone

2024-10-14 14:51 UTC, sitaram-kalluri commented
> @sitaram-kalluri I think the logic here is faulty. Consider the following scenario. . User onboards an atsign using onboard command - standard atKeys file created . On the same host, the user attempts an enrollment using the enroll command leaving the keys file as default . isWritable confirms the standard atKeys file is writable, and then deletes it . the original atKeys file is now gone

@gkc : The keys file is mandatory for the enroll command. Attaching the log snippet below
```
sitaram@sitaram-ThinkPad-E14:~/IdeaProjects/atsign/core/at_libraries/packages/at_onboarding_cli/bin$ dart activate_cli.dart enroll -s ABC123 -p wavi -d local -n wavi:rw -a @alice🛠 -r vip.ve.atsign.zone
Argument error for command enroll: The --keys option is mandatory for the "enroll" command
Usage: enroll
    -s, --passcode (mandatory)      The passcode to present with this enrollment request.
```

The below condition in the enroll method ensure the atKeys file path is mandatory:
```dart
@visibleForTesting
Future<void> enroll(ArgResults argResults, {AtOnboardingService? svc}) async {
  if (!argResults.wasParsed(AuthCliArgs.argNameAtKeys)) {
    throw ArgumentError('The --${AuthCliArgs.argNameAtKeys} option is'
        ' mandatory for the "enroll" command');
  }
  ```

Further, if the user gives the same atKeys filepath for enroll command as of the original atKeys, then it would return an error stating the atKeys file exists but does not delete the original atKeys file.

2024-10-15 10:50 UTC, gkc requested changes
@sitaram-kalluri you state
> Further, if the user gives the same atKeys filepath for enroll command as of the original atKeys, then it would return an error stating the atKeys file exists but does not delete the original atKeys file.

However, you have removed that specific check for the file already existing

2024-10-15 10:50 UTC, gkc commented on packages/at_onboarding_cli/CHANGELOG.md
> +- When submitting an enrollment request, check for write permissions of AtKeys file path.
add 'fix: ' at the start of this comment please

2024-10-15 10:51 UTC, gkc commented on packages/at_onboarding_cli/lib/src/cli/auth_cli.dart
> -    stderr.writeln('Error: atKeys file ${f.path} already exists');
The above check should not have been removed

2024-10-15 10:52 UTC, gkc commented on packages/at_onboarding_cli/lib/src/cli/auth_cli.dart
> -    stderr.writeln('Error: atKeys file ${f.path} already exists');
For maintainability purposes. It needs to be made clear to the reader precisely what is happening here. Burying this as an exception in a method called 'isWritable' makes the code confusing

2024-10-15 11:55 UTC, sitaram-kalluri commented on packages/at_onboarding_cli/lib/src/cli/auth_cli.dart
> -    stderr.writeln('Error: atKeys file ${f.path} already exists');
Sure Gary, Added the "f.existsSync()" check back.

2024-10-15 11:57 UTC, sitaram-kalluri commented on packages/at_onboarding_cli/CHANGELOG.md
> +- When submitting an enrollment request, check for write permissions of AtKeys file path.
Added "fix:" in the changelog.md

2024-10-15 12:06 UTC, gkc requested changes

2024-10-15 12:06 UTC, gkc commented on packages/at_onboarding_cli/lib/src/cli/auth_cli.dart
> +    file.createSync(recursive: true);
I believe we should keep the `exclusive:true` here also, but allow the PathExistsException to be thrown. I'm a bit uncomfortable with a method called 'isWritable' possibly deleting a file

Maybe a better approach would be for this method to handle each case (file exists, file doesn't exist) differently
- if file exists, try opening it for FileMode.writeOnlyAppend
- if file doesn't already exist, try creating it and then removing it

2024-10-17 02:59 UTC, sitaram-kalluri commented on packages/at_onboarding_cli/lib/src/cli/auth_cli.dart
> +    file.createSync(recursive: true);
@gkc : 
- Renamed "isWritable" method name to "canCreateFile".
- Added `exclusive:true` when creating a file and rethrowing the PathExistsException.

Please review and let me know if any further changes are required.

2024-10-17 13:40 UTC, gkc approved these changes

2024-10-17 13:40 UTC, merged