fix: Changes in at_commons related to public key hash and implement sha512 hashing algo in at_chops
atsign-foundation/at_libraries pull request #711
Opened 2024-11-18 12:29 UTC by sitaram-kalluri

**- What I did**
Changes in at_chops:

 - Implement SHA512 hashing algorithm in at_chops.
 - In at_chops_impl.dart, introduce "hashWith" static method which will take a hashing algorithm as input and return the hashed value the given input.

Changes in at_commons:
 - In PublicKeyHash.dart,  replace "PublicKeyHashingAlgo" enum with String which holds the hashing algo. This is because the "PublicKeyHashingAlgo" is a duplicate of "HashingAlgoType" enum and have an overhead of converting PublicKeyHashingAlgo type to HashingAlgoType in at_chops to hash the data. 
- Updated the existing unit tests accordingly.

2024-11-19 10:29 UTC, murali-shris requested changes
C

2024-11-19 10:29 UTC, murali-shris commented on packages/at_chops/lib/src/algorithm/default_hashing_algo.dart
> +  String hash(List<int> data, {covariant HashParams? hashParams}) {
please write unit test for this hash method

2024-11-19 10:38 UTC, sitaram-kalluri commented on packages/at_chops/lib/src/algorithm/default_hashing_algo.dart
> +  String hash(List<int> data, {covariant HashParams? hashParams}) {
Added unit test for SHA512 hashing algo.

2024-11-20 06:36 UTC, murali-shris approved these changes

2024-11-20 07:10 UTC, merged